# Site settings
baseurl = "http://www.eginez.xyz"
languageCode = "en"
title = "E's Musings"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/eginez\">Esteban Ginez</a> 2018"
googleAnalytics = "UA-105828460-1"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
  url = "https://twitter.com/StbG"
  fa_icon = "fa-twitter"

[[params.social]]
  url = "https://github.com/eginez"
  fa_icon = "fa-github"
