# Hugo deployment script based
# https://www.karelbemelmans.com/2016/10/deploying-a-hugo-website-to-amazon-s3-using-bitbucket-pipelines/
version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      # specify the version
      - image: karelbemelmans/pipelines-hugo
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: hugo
      - run: aws s3 sync --delete public s3://www.eginez.xyz
